[tool.poetry]
name = "advent-of-code"
version = "0.1.0"
description = "Advent of Code projects"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "*"
requests = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"